server:
  port: 12000 #配置中心的端口号
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/chuanzhizhy/config47.git
  rabbitmq:
    host: 192.168.242.137
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh